### ISSUE TITLE
RestComm Geolocation Rest API Implementation

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#637] opened 2015-11-10 15:35 UTC
Implement Design specified in #636

**Comment by deruelle** [comment] 2015-11-10 15:36
This should include tests in the restcomm.testsuite that Emulate the GMLC MLP (since it is HTTP Based you can use wiremock as we do in DID Provisioning Unit tests) so we don't need to do any work yet on GMLC until the API is implemented and tested.

**Comment by FerUy** [comment] 2016-04-21 18:31
Closed with #1013

**Comment by gvagenas** [comment] 2016-05-13 13:56
Open until review and merge of PR #1013

**Comment by ghjansen** [comment] 2016-05-18 05:50
Hi @FerUy and @gvagenas , here follow some considerations from my review for this PR. 
@FerUy, please consider that my knowledge about Geolocation particularities is really limited, so feel free to contest and elaborate on arguments about the content below.

To improve the visualization of all endpoints in Geolocation API, i created the following table considering all possible formations in the way i understood as intended.
@FerUy please check if you see some invalid combination and we adapt this post as needed.

Base path | Type | Sufix | Method | Response  
----------|------|-------|--------|---------
/Accounts/{accountSid}/Geolocation | n/a | n/a | GET | XML List
/Accounts/{accountSid}/Geolocation.json | n/a | n/a | GET | JSON List
/Accounts/{accountSid}/Geolocation | /Immediate | n/a | GET | XML List
/Accounts/{accountSid}/Geolocation | /Immediate | n/a | POST | XML Element
/Accounts/{accountSid}/Geolocation | /Immediate.json | n/a | GET | JSON List
/Accounts/{accountSid}/Geolocation | /Immediate.json | n/a | POST | JSON Element
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid} | GET | XML Element
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid} | POST | XML Element
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid} | PUT | XML Element
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid} | DELETE | HTTP 204
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid}.json | GET | JSON Element
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid}.json | POST | JSON Element
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid}.json | PUT | JSON Element
/Accounts/{accountSid}/Geolocation | /Immediate | /{sid}.json | DELETE | HTTP 204
/Accounts/{accountSid}/Geolocation | /Notification | n/a | GET | XML List
/Accounts/{accountSid}/Geolocation | /Notification | n/a | POST | XML Element
/Accounts/{accountSid}/Geolocation | /Notification.json | n/a | GET | JSON List
/Accounts/{accountSid}/Geolocation | /Notification.json | n/a | POST | JSON Element
/Accounts/{accountSid}/Geolocation | /Notification | /{sid} | GET | XML Element
/Accounts/{accountSid}/Geolocation | /Notification | /{sid} | POST | XML Element
/Accounts/{accountSid}/Geolocation | /Notification | /{sid} | PUT | XML Element
/Accounts/{accountSid}/Geolocation | /Notification | /{sid} | DELETE | HTTP 204
/Accounts/{accountSid}/Geolocation | /Notification | /{sid}.json | GET | JSON Element
/Accounts/{accountSid}/Geolocation | /Notification | /{sid}.json | POST | JSON Element
/Accounts/{accountSid}/Geolocation | /Notification | /{sid}.json | PUT | JSON Element
/Accounts/{accountSid}/Geolocation | /Notification | /{sid}.json | DELETE | HTTP 204

Assuming the table above as the intended scenario, the follow adjustments are required in the current implementation:

- **1** - Remove `@DELETE` support for `/Immediate`.
- **2** - Switch method used in `@GET` for `/Immediate` to return a list of elements, or remove `@GET` support for this endpoint.
- **3** - Remove `@PUT` support for `/Immediate`.
- **4** - Remove `@DELETE` support for `/Immediate.json`.
- **5** - Switch method used in `@GET` for `/Immediate.json` to return a list of elements, or remove `@GET` support for this endpoint.
- **6** - Remove `@DELETE` support for `/Notification`.
- **7** - Switch method used in `@GET` for `/Notification` to return a list of elements, or remove `@GET` support for this endpoint.
- **8** - Remove `@PUT` support for `/Notification`.
- **9** - Remove `@DELETE` support for `/Notification.json`.
- **10** - Switch method used in `@GET` for `/Notification.json` to return a list of elements, or remove `@GET` support for this endpoint.
- **11** - Check how multi-tenancy must be applied to `Geolocation` records (currently, only the owner has access to its own records).
- **12** - Refactor method `GeolocationEndpoint.validateGeolocationType(final MultivaluedMap<String,String>)`, replacing the current parameter by `Geolocation.GeolocationType` placing the validation of this parameter inside the method (currently, the method is only throwing an exception instead of actualy perform the validation and then throw an exception - if needed).
- **13** - Refactor the current validation of parameters when processing requests to create a new `Geolocation` entity, avoiding error responses in the same format of the successfull ones. Currently, the method `GeolocationEndpoint.validateCreateParams(final Sid, final MultivaluedMap<String,String>, Geolocation.GeolocationType)` returns a `Geolocations` object independent of the validation result, so in case of fail, the response will contain a `Geolocation` entity in JSON or XML format and one of its attributes will carry the error message. THe problem in this approach is that there is no correspondent error in the protocol layer (a HTTP error code) and the response contains attributes that should be generated with the entity just in case of success, like `sid`, `date_created`, `date_updated` and `uri`, so if the one who requested this operation may think that the `sid` in the response represents a database record, when actually it was only the attribute of a temporary `Geolocation` object, created in memory only. The following suggestions are based in the standards used accross all endpoints, and may help to adjust the current approach (the order of the items must be considered):
	- **13.1** turn the method `GeolocationEndpoint.validateCreateParams(final Sid, final MultivaluedMap<String, String>, Geolocation.GeolocationType)` into `void`;
	- **13.2** move the validation of the `geolocationType` from the method `GeolocationEndpoint.validateGeolocationType(final MultivaluedMap<String, String>)` to method `GeolocationEndpoint.validateCreateParams(final Sid, final MultivaluedMap<String, String>, Geolocation.GeolocationType)` (check item **12** first);
	- **13.3** remove the method `GeolocationEndpoint.validateGeolocationType(final MultivaluedMap<String, String>)`;
	- **13.4** rename the method `GeolocationEndpoint.validateCreateParams(final Sid, final MultivaluedMap<String, String>, Geolocation.GeolocationType)` to `validate`;
	- **13.5** remove `logger.info()` calls inside `validate` method to avoid log inflation and preserve server's filesystem;
	- **13.6** replace each **`return`** in `validate` method by a **`throw new`** followed by a convenient exception capable to transport the information and error message required to include in the response (in case of fail);
	- **13.7** remove unnecessary use of **`try`** and **`catch`** clauses in `validate` method;
	- **13.8** remove method `Geolocation.rejectGeolocationRequest`;
	- **13.9** remove method `Geolocation.buildIncorrectGeolocationRequest`;
	- **13.10** remove method `Geolocation.failedGeolocationRequest`;
	- **13.11** remove method `Geolocation.buildIncorrectGeolocationUpdateRequest`;
	- **13.12** remove method `Geolocation.incorrectGeolocationUpdateRequest`;
	- **13.13** change the logic in `Geolocation.putGeolocation` to call the method `createFrom` after call the method `validate`, so `createFrom` will be reached only if there is no validation errors;
	- **13.14** remove the existent `createFrom` method and rename method `buildGeolocation` to `createFrom`;
	- **13.15** in 'putGeolocation' method, replace the logic based on `geolocation.getResponseStatus` by a `return` which must use a HTTP error code based on `validate` result, ensuring that the validation block is placed before the creation of the `Geolocation` entity, like in the `putX` method present in other endpoints;
	- **13.16** review and apply the previous suggestions also for method `GeolocationEndpoint.updateGeolocation` and the structures under it.
- **14** - The method `MybatisGeolocationDao.removeGeolocations` seems not used, may consider to remove this method.

@FerUy some things are complex to explain, so please feel free to ping me if something is not clear.
@gvagenas your considerations are also very welcome here when you manage some free cycles.

**Comment by FerUy** [comment] 2016-05-18 15:05
@ghjansen I will ping you to discuss some of your proposals, so as to keep consistency with the already documented and agreed specification. Also, bear in mind that at this stage some operations are just "simulating" what a GMLC or analog location entity will provide as location information once we wired them.

**Comment by FerUy** [comment] 2016-09-22 17:46
Previous commit recreated all files and follows the guidelines of PR #1013 (including fixes after initial peer reviewing suggestions by @ghjansen and @jaimecasero), which became a little outdated (a mariadb update script is not necessary anymore and needed to add the needed adjustment to new DaoManagerMock class). As stated in the commit, a new PR on this new branch will be done once wiring with GMLC.

**Comment by FerUy** [comment] 2017-02-02 13:47
Closed as for PR #1717 peer review and merge with master.

**Closed by FerUy** 2017-02-02 13:47 UTC
Labels: 2. Enhancement, highlight, Location
