### ISSUE TITLE
Call/message usage reporting service for community edition

### ISSUE THREAD

**Issue by ivelin** [RestComm/Restcomm-Connect#376] opened 2015-08-05 15:45 UTC
Related to #283 

Related IRC discussion:

''
gvag: You mean the service that will collect the stats?
[10:25am] gvag: I think we have to go with Graylog for that, or a similar application
[10:26am] ivelin: yes, the cloud service
[10:27am] ivelin: Graylog is the tool, but I’m also thinking about the live service
[10:27am] gvag: I think Graylog, which is based on ElasticSearch but provides many nice features, is perfect for what we need
[10:27am] gvag: Can you elaborate on what you mean live service?
[10:28am] ivelin: something like stats.restcomm.com where we show a worldwide map of monthyl, weekly calls/messages served by restcomm
[10:28am] ivelin: anonymous global usage data
[10:30am] charles-r: ivelin, wouldn't some people object to us collecting data about their running Restcomm instance?
[10:31am] gvag: I am not sure about this service and what will take to build it. We can discuss it with Alex or Orestis for them to build something on AngularJS. Because I guess we don't want to have Graylog in public, unless if we can customize it completely and we provide our own logo etc
[10:31am] ivelin: charles-r , yes its optional
[10:32am] abhayani: we have more challenges here. Most of the enterprise doesn't like direct internet connection to their servers
[10:32am] abhayani: so may be an alternative could be to periodically print in logs
[10:33am] abhayani: and as and when net is available push only these lines from logs to central server
[10:33am] abhayani: just thinking about various possibilities
[10:33am] abhayani: as we want to have same for other legacy products too
[10:35am] charles-r: We could start by showing number of downloads and from how many countries in the world.
[10:35am] abhayani: gvag, I am thinking if this should be separate project which can reused by any product
[10:35am] gvag: abhayani, the monitoring services provided by Restcomm is a feature for enterprise monitoring, so customers can run their own elasticsearch or graylog or whatever monitoring server, to collect stats from Restcomm. On the side, we will collect anonymous call data for a statistics
[10:36am] gvag: abhayani, what do you have in mind for that? The monitoring service, checks for Restcomm live calls by receiving call events etc, this is something very specific to Restcomm.
[10:37am] gvag: These stats are exposed to any monitoring tool by the REST API, very Restcomm specific also
[10:37am] gvag: I don't see any other way that can be used in other projects
[10:38am] ivelin: the problem with downloads is that its hard to monitor nowadays
[10:38am] ivelin: between torrents and other sources, its hard to tell
[10:39am] ivelin: but call/message stats is something that I think will be more representative
[10:39am] ivelin: despite all the limitations you bring up.
[10:39am] ivelin: yes, some machines are behind VPN without any internat access
[10:39am] ivelin: but most are online
[10:39am] ivelin: we aren’t looking for a perfectly accurate number
[10:39am] ivelin: just a ballpark representation
[10:40am] ivelin: Do we handle tens or hundreds of millions of messages / calls per day ?
[10:41am] ivelin: let me open a new issue for 7.4
[10:41am] abhayani: for legacy we have like 100's of millions of SMS per day
[10:42am] ivelin: yes, so then overall do we handle 100’s of millions or billions?
''

**Comment by deruelle** [comment] 2016-05-03 12:14
The goal is to design and implement a reusable library that can collect and send stats usage on SIP or SS7 calls and (SIP or SMPP or SS7) messages as well as charging/billing events (diameter) going through a JVM to a reliable hosted service (that you would design as well). 
This library will eventually be part of all the main Restcomm projects

**Comment by rlimonta** [comment] 2016-05-03 13:36
Awsome! I will start today!

I will study this item and return in case of questions.

Do you use a specific tool for the design?

Regards.

Ricardo Limonta

2016-05-03 9:14 GMT-03:00 Jean Deruelle <notifications@github.com>:

> The goal is to design and implement a reusable library that can collect
> and send stats usage on SIP or SS7 calls and (SIP or SMPP or SS7) messages
> as well as charging/billing events (diameter) going through a JVM to a
> reliable hosted service (that you would design as well).
> This library will eventually be part of all the main Restcomm projects
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RestComm/Restcomm-Connect/issues/376#issuecomment-216509573>
>



-- 
Ricardo Limonta

**Comment by deruelle** [comment] 2016-05-03 15:09
We try to use PlantUML for design and Google Docs or asciidoc in general so far

**Comment by rlimonta** [comment] 2016-05-05 14:51
Jean,

Currently the events from all stacks (SIP, SS7, SMPP, etc) are created via Log4j?

If so, I think that the collector could be a custom Log4J Appender, which receive these events and would send to the Stats Platform.

If we have different sources, I'll use a generic strategy for the collector.

**Comment by deruelle** [comment] 2016-05-05 14:58
@rlimonta that's correct. that may be a good idea but 3 points to consider: 

1. in WARN or ERROR, messages are not logged at all so in production env you would get no stats
2. Sending all events with the content of message may be overkill in terms of data sent, just counters at a configurable interval should be enough.
3. the content of messages will not be anonymized which is a concern, we don't want to log users, IPs etc.

**Comment by rlimonta** [comment] 2016-05-05 15:55
Ok  @deruelle , these points are very important!

We can create a specific log level (like a Level.STATS) and a specific appender (json format).

In this way you can decide in your stack which message goes to the central environment.

**Comment by deruelle** [comment] 2016-05-05 17:36
@rlimonta do you have pseudo code of how it would like and what the various projects would have to add in the code ?

**Comment by rlimonta** [comment] 2016-05-05 19:10
@deruelle follows two examples:

//String Message
logger.log(STATS, "string message");
result:
{
    "logger":"org.mobicents.servlet.restcomm.sms.SmsService",
    "timestamp":"1376681196470",
    "level":"STATS",
    "thread":"main",
    "message":"string message"
}

//Object Message (Eg. instance of SmsMessage object)
//In this scenario it's possible to customize toString() method.
logger.log(STATS, smsMessage);

result:
{
    "logger":"org.mobicents.servlet.restcomm.sms.SmsService",
    "timestamp":"1376681196470",
    "level":"STATS",
    "thread":"main",
    "message":"[sms.toString()]"
}

If this approach does not satisfy, I think of another strategy for the collector.

**Comment by deruelle** [comment] 2016-05-05 20:37
@rlimonta  This seems to be a clean, simple and effective approach to me although I have one question, some of our projects are reusing others, by example, JAIN SIP Stack is used by SIP Servlets and SIP Servlets is used by Restcomm-Connect. If each layer is using this, we would have recorded 3 times the same call or message when we reach Restcomm-Connect layer, how would you prevent that ?

Another comment, if we adopt that approach, we should probably define a number of Utility Stats classes in a common library (https://github.com/RestComm/commons) that implement the toString that you're suggesting and represent the main possibilities : Audio Calls (# of them, # of minutes, ..), Video Calls, Messages (SMS, IP), Billing, ... so not every project create a different convention and it becomes a mess on the server side ?

**Comment by rlimonta** [comment] 2016-05-06 13:52
@deruelle I believe it is better to think of a different approach. the STATS not only host system logs, but also data billing, call quality, SMS messages and others. It should be more flexible in the data structure.

I will design the collector as a API that can take any object (like a java bean) and transforms it into JSON, persisting in the central system.

In this way we will have a flexible statistics system that will be able to be used by any stack.

For the back-end we should have a local environment to host the data that is able to replicate these data to the cloud, right?

I'll finish the solution design today.

**Comment by deruelle** [comment] 2016-05-06 15:54
@rlimonta Thanks. Looking forward to the new design. 

For the backend, I would like to have it hosted directly on cloud. 
As a first step we can investigate using Google Analytics as a potential solution to report back to ?
We could then think of using platforms such as Openshift or AWS Lamba to host the backend as a second step or if Google Analytics is not possible/too restricting. 

Feel free to share your thoughts on the backend as well.

**Comment by rlimonta** [comment] 2016-05-06 16:27
@deruelle I was considering this point:

_"[10:32am] abhayani: we have more challenges here. Most of the enterprise doesn't like direct internet connection to their servers."_

So I considered primarily in having a local repository.

But if we consider the cloud as the first alternative, the solution is more simple.

**Comment by deruelle** [comment] 2016-05-06 16:34
@rlimonta good catch. Let's still proceed with cloud solution first to iterate faster and not overdesign. We can think of a local proxy for onsite customers later.

**Comment by rlimonta** [comment] 2016-05-06 16:35
@deruelle Ok.

**Comment by rlimonta** [comment] 2016-05-06 21:53
@deruelle I have created an overview of the structure of the Stats module and would like your evaluation.

https://docs.google.com/document/d/1WSuvZ68RXeTSOSW7bXF62vjLZagHu5n1TYLbhDwGLyQ/edit

I believe that _Google Cloud Data Store_ and _Elastic_ are appropriate because they operate under the schema less concept, essential to the requirement.

If you agree, I will continue working on the module design.

**Comment by deruelle** [comment] 2016-05-12 13:32
I'm sorry @rlimonta. I was not able to review the design yet. I have been a bit overloaded on other tasks. I'll try to review it this week.
@gvagenas may have a look as well.

**Comment by rlimonta** [comment] 2016-05-12 14:24
No problem Jean :)

Em quinta-feira, 12 de maio de 2016, Jean Deruelle <notifications@github.com>
escreveu:

> I'm sorry @rlimonta <https://github.com/rlimonta>. I was not able to
> review the design yet. I have been a bit overloaded on other tasks. I'll
> try to review it this week.
> @gvagenas <https://github.com/gvagenas> may have a look as well.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/RestComm/Restcomm-Connect/issues/376#issuecomment-218757814>
>


-- 
Ricardo Limonta

**Comment by deruelle** [comment] 2016-05-16 16:12
@rlimonta realized I don't have the rights to see it. just requested access.

**Comment by deruelle** [comment] 2016-05-16 19:55
@rlimonta I just commented on your comment. It's an interesting first draft but a bit too high level, I would like you to provide more details as described in my comments in the document.
Also did you investigate using a solution such as https://aws.amazon.com/lambda/ ?

**Comment by gvagenas** [comment] 2016-05-16 19:57
@rlimonta please provide me access to check the document also.

Thanks
George

**Comment by rlimonta** [comment] 2016-05-17 11:50
@deruelle @gvagenas Guys, I will improve the module design until end of day. 
I looked at the Amazon Lambda yesterday, and I believe we can use it. The idea is similar to google and elastic, but we can use as a first option.

**Comment by rlimonta** [comment] 2016-05-17 23:03
@deruelle I made a more detailed analysis about the AWS Lambda, and we have two possible scenarios:

**1) Implement handler components and process persistence tasks into the cloud.**
**Pros:** Improve throughput automatily.
**Cons:** Need to pre-define our data types (POJOs).
See: http://docs.aws.amazon.com/lambda/latest/dg/java-programming-model-req-resp.html

**2) Implement the persistence directly to DynamoDB.**
**Pros:** Flexibility in the data structure. In this case the stats module would make the transformation of the data types (POJO) into JSON locally, persisting directly into DynamoDB.
**Cons:** Process overhead.

I would like to know your opinion about it.

**Comment by deruelle** [comment] 2016-05-19 07:51
@rlimonta on 2) what do you mean by process overhead ? 

I tend to favor 2) as if we need to move the data to a different structure it would be easier to migrate from DynamoDB to another DB let's say cassandra or whatever. Also Java Serialization for 1) is known not to be terribly efficient.

**Comment by rlimonta** [comment] 2016-05-19 17:16
@deruelle The basic difference between option 1 and 2 are in the persistence processing environment. In option 2 the thread runs into the cloud, with elastic scalability.

In option 2, the threads will be run on the local server. In this case, we need to implement buffer mechanisms to decrease round-trips to the cloud database. 

I think is a good idea implement asynchronous service to, what do you think?

My basic idea is implement connectors to enable the use of different databases like Mongodb, Cassandra, DynamoDB and others.

**Comment by deruelle** [comment] 2016-05-19 20:47
sounds good @rlimonta. looking forward to the second iteration of the design !

**Comment by rlimonta** [comment] 2016-05-19 21:16
@deruelle  Ok, thank you!

**Comment by rlimonta** [comment] 2016-05-22 22:43
@deruelle I improved the document detailing the module structure.

https://docs.google.com/document/d/1WSuvZ68RXeTSOSW7bXF62vjLZagHu5n1TYLbhDwGLyQ/edit

I saw that other modules uses akka, so I adopted the same strategy.

I'm waiting your evaluation.

**Comment by deruelle** [comment] 2016-05-23 21:27
Thanks @rlimonta I commented further on the solution.

I'm thinking for the client side we can recommend or wrap http://metrics.dropwizard.io/3.1.0 for the most popular data we have ie SMS/Messages, Calls, Billing Events and send metrics regularly to the backend server.

**Comment by deruelle** [comment] 2016-05-25 08:02
Basically the goal is to have a simple library to start with that will gather number of calls, SMS and billing events and send it periodically to a central server. A website will use this information to display the number of total calls, SMS and billing events that went through all the Restcomm projects that integrated the library across the globe.

**Comment by rlimonta** [comment] 2016-05-27 13:26
@deruelle I studied the metrics library and I believe it is a good idea.

What you think on the central server? 

It will be a our environment? or not?

**Comment by deruelle** [comment] 2016-05-27 13:29
@rlimonta I don't mind going with something that is not our environment, something like openshift may be good as well. The faster the better so we can start collecting community metrics as soon as possible. We can then iterate on refining the library and solution as we learn more.

**Comment by rlimonta** [comment] 2016-05-27 13:42
@deruelle Ok Jean, I'll work on that idea right now.

**Comment by rlimonta** [comment] 2016-05-30 16:59
@deruelle I implemented a client module using the Metrics library and commited into my github.

https://github.com/rlimonta/restcomm-stats

We need to define the strategy for the back-end. I like the idea of using OpenShift with MongoDB and Restful WebServices.

I would like your opinion about it. 

After we define, I'll start this layer.

**Comment by deruelle** [comment] 2016-05-31 21:25
hi @rlimonta this seems like a good start. I'm still a bit unclear on how those will get transferred to the server side so I think if you can start to move forward with the backend design that would be great. Let's create another github project for that but using OpenShift with MongoDB and REST API sounds like a good direction to me to start with and iterate quickly.

**Comment by rlimonta** [comment] 2016-06-01 00:27
@deruelle I´ll start the back-end. 

I think it's interesting include additional informations into statistics, like Source IP Address, because our back-end hosts statistics from different platforms, right?

We I'll talk about it later.

**Comment by deruelle** [comment] 2016-06-01 07:52
We need to be careful, this can be seen as a privacy issue. We can push the country or/and city though, I think

**Comment by deruelle** [comment] 2016-06-07 07:18
@rlimonta just checking if you need more insights or if there is any blockers ?

**Comment by rlimonta** [comment] 2016-06-07 12:41
@deruelle No, thanks. I will finish on this week. 
Do you have any preference about WebContainer for the back end? I´m using the Glassfish right now, but I can change.

**Comment by deruelle** [comment] 2016-06-07 15:10
@rlimonta yes let's use JBoss instead as most of our platform is using JBoss and it can run well on OpenShift.

**Comment by rlimonta** [comment] 2016-06-07 15:31
Ok. thanks!

**Comment by rlimonta** [comment] 2016-06-14 12:32
@deruelle I finished the implementation of client and core modules and committed on my Github.

I used a flexible strategy in order to include new attributes automatically, through Maps.

Now I'll work on documentation and web app to display graphics.

After that, I'll publish into the OpenShift.

**Comment by deruelle** [comment] 2016-06-19 18:52
@rlimonta I'm travelling right now so will not be able to review before last week of June. Do you want me to create separate github projects so you can push there ?

**Comment by rlimonta** [comment] 2016-06-20 13:00
@deruelle That would be good! Thank you.

**Comment by deruelle** [comment] 2016-06-30 14:37
@rlimonta sorry about the delay, just came back from business travels. Do you want to provide the https://github.com/rlimonta/restcomm-stats project as a new folder in https://github.com/RestComm/commons ?

For the server side I created https://github.com/RestComm/statistics-service and added you as collaborator there, you can accept invitation at https://github.com/RestComm/statistics-service/invitations.

Were you able to make progress on documentation, web app to display graphics and OpenShift ?

**Comment by rlimonta** [comment] 2016-07-01 15:05
@deruelle I'll finish on this weekend and publish on the OpenShift.

We need to define a unique id for each environment. Do you have any suggestion?

**Comment by deruelle** [comment] 2016-07-03 20:33
Thanks @rlimonta. 

Can you describe what you mean by what an environment means here and why a unique id is required ?

**Comment by rlimonta** [comment] 2016-07-03 21:38
@deruelle The stats module will receive information from various environments. If we want to have a vision for the specific environment, I think it would be important to have a unique identifier. Otherwise, we may forget this item.

**Comment by deruelle** [comment] 2016-07-04 07:01
@rlimonta Can we use the project name and version (ie Restcomm-Connect 7.7.0 by example) has a unique identifier and potentially include it also in the information sent ? This would allow us to break down per project and per version which system is sending more traffic and see the penetration of particular versions over others like Android and Apple are showing the penetration of particular versions of their OS

**Comment by rlimonta** [comment] 2016-07-04 11:52
@deruelle Yes, it´s possible!

**Comment by deruelle** [comment] 2016-07-07 08:51
@rlimonta great let me know when ready then and when you pushed the code to the new repo

**Comment by rlimonta** [comment] 2016-07-07 14:50
@deruelle Hello Jean, I'm sorry for the delay, I had a little contretemps in the last days.
I need just finish the dashboards charts, and I'll finish today.

**Comment by rlimonta** [comment] 2016-07-08 13:24
@deruelle I finished the implementation of the web module. Today I will publish into the OpenShift.

I tried to commit the cliente module into commons folder, but I'm not allowed to create sub-folders. You could create a folder called statistics?

I'm sending some screenshots from web module.

Best regards.

![stats_dashboard](https://cloud.githubusercontent.com/assets/19157645/16688784/17f907b0-44f6-11e6-8d0f-d371dc923020.png)
![stats_login](https://cloud.githubusercontent.com/assets/19157645/16688785/17fdf7de-44f6-11e6-8c7a-e2439f9b7e44.png)

**Comment by deruelle** [comment] 2016-07-08 16:29
this look great @rlimonta ! 
Can you do a pull request on the commons project ? That's how we accept new code usually and allow us to do peer reviews as described in the Open Source Playbook.

Is the data shown in the graph available through a REST API ? If multiple VMs are running with the commons stats module activated I assume the server side is concatenating results from all VM over time as well right ?

**Comment by rlimonta** [comment] 2016-07-08 20:13
@deruelle I committed the statistics-service module into repository successfully. About the commons module, I can't make a pull request. I need select one source branch first.

About your questions:
_**"Is the data shown in the graph available through a REST API ?"**_
Yes, it's totally possible access through a REST API, I can implement the @GET methods.

_**"If multiple VMs are running with the commons stats module activated I assume the server side is concatenating results from all VM over time as well right ?"**_
The system concatenating results from all VMs and grouping by timestamp and key. 

Eg. 
**VM1 sent:** 
_{
    "count" : 4560,
    "key" : "sip-requests",
    "timestamp" : NumberLong(1467920534273)
}_
**VM2 sent:** 
_{
    "count" : 5350,
    "key" : "sip-requests",
    "timestamp" : NumberLong(1467920534273)
}_

At chart we will have **9910** **sip-request** at timestamp **1467920534273**.

One important thing is about the key. The Key is dynamic, and we have possibility to create new keys automatically at the client side.

Eg. Client Side
`//define metric name
Counter counter = metrics.counter("sip-request");`

**Comment by deruelle** [comment] 2016-07-11 17:45
@rlimonta did you follow the procedure at https://docs.google.com/document/d/1RZz2nd2ivCK_rg1vKX9ansgNF6NpK_PZl81GxZ2MSnM/edit#heading=h.mcjitemt6ng1 for creating your own fork, committing to it and then doing a Pull Request from it ?

> Yes, it's totally possible access through a REST API, I can implement the @GET methods.

Great, let's do it

Great on concatenation. 

Did you write some tutorial on how to deploy the server side to OpenShift by example ?

**Comment by rlimonta** [comment] 2016-07-11 21:50
@deruelle Thank you for your response, now I got it :)

About the OpenShift, we can do in two ways:

_01) I can create a environment associated with  my account.

02) You can create an environment associated with a project account. We need Wildfly 10 and MongoDB._

One important thing is about the hostname. The client module sends messages to http://stats.restcomm.com:8080/statistics/rest/. 

This address is in a properties file (config.properties) and can be changed if necessary.

**Comment by deruelle** [comment] 2016-07-12 20:03
@rlimonta let me try to create my own environment on OpenShift to test the documentation. 
Can you create a tutorial in asciidoc format push it to the statistics-service repo ?

**Comment by rlimonta** [comment] 2016-07-12 21:42
@deruelle Yes, I will work on documentation and @GET methods.

**Comment by deruelle** [comment] 2016-07-15 15:08
Thanks @rlimonta. Looking forward to set it up and start testing

**Comment by zahidMed** [comment] 2016-07-18 15:14
@deruelle 
I think it's too late for proposal. But I think that stats should be devided into differents layers (ObjectType) each ObjectType contains counters according to the nature of this layer (number of success requests, nbr of failure requests, latency ...). kpi4j was developed for that purpose and can be used in all the modules. the ObjectType activation is done through the config file and I can adapt it to your need.
https://github.com/zahidMed/kpi4j

**Comment by rlimonta** [comment] 2016-07-19 00:43
@deruelle I finished the implementation of @GET methods and improved the dashboard graphics. I created a single chart by metric.

Now I need to finish the Installation Guide. I have all screenshots and need to finish the doc.

![screen shot 2016-07-18 at 9 32 56 pm](https://cloud.githubusercontent.com/assets/19157645/16934823/984a0558-4d30-11e6-9fab-a3d5aa8fb97d.png)
![screen shot 2016-07-18 at 9 33 19 pm](https://cloud.githubusercontent.com/assets/19157645/16934828/9e119ee2-4d30-11e6-8cfc-ad9ad86fabb5.png)

**Comment by deruelle** [comment] 2016-07-21 08:33
@rlimonta looking better by the day. Looking forward to the doc to set it up !

**Comment by rlimonta** [comment] 2016-07-21 12:14
@deruelle In the last three days I had problems accessing OpenShift environment.

I do not know if this is true for all plans or only for free instances.

What do you think of using another alternative like Doker, AWS, etc ?

I received this message:
![screenshot from 2016-07-20 19_20_09](https://cloud.githubusercontent.com/assets/19157645/17022279/74e55924-4f23-11e6-88ca-f6885c2141ec.png)

**Comment by deruelle** [comment] 2016-07-21 12:37
It seems to work on my side. But I'm fine to have a Docker guide to start with.

**Comment by rlimonta** [comment] 2016-07-21 12:48
Ok.

**Comment by deruelle** [comment] 2016-07-28 09:00
@rlimonta any news on this yet ?

**Comment by deruelle** [comment] 2016-08-04 08:49
@rlimonta were you able to wrap this up by any chance ?

**Comment by rlimonta** [comment] 2016-08-04 10:22
@deruelle I apologize for the delay, but I had to travel to work in the last two weeks. I need only finalize the document. I'll work on it and send you until the weekend. The OpenShift environment is running fine now!

**Comment by rlimonta** [comment] 2016-08-09 01:26
@deruelle I wrote the document README.md explaining the deployment process into OpenShift environment. If you have any comments or suggestions, please feel free to let me know.

**Comment by deruelle** [comment] 2016-08-18 16:13
Thanks @rlimonta. I just returned from vacations. Let me check that out.

**Comment by rlimonta** [comment] 2016-08-18 17:54
@deruelle Ok Jean, feel free to any suggestion.

**Comment by deruelle** [comment] 2016-08-23 09:48
Thanks @rlimonta I was able to get it up and running and push some test data to it but I see that when I try to change the date, the end date doesn't seem to be taken into account or something else

![screenshot from 2016-08-23 11-42-05](https://cloud.githubusercontent.com/assets/54279/17887431/be5c073e-6926-11e6-8c98-1797bc8452ed.png)

Also I tried the GET API on http://statistics.restcomm.com/rest/counter/1471167956/1471945556/sip-invites

Shall we protect the GET API under the same username and pwd as the UI by the way ?

**Comment by deruelle** [comment] 2016-08-23 17:36
Also restarting the OpenShift application led to loosing all the information. It seems counters are back to 0.

**Comment by deruelle** [comment] 2016-08-24 12:35
@rlimonta 

> Also I tried the GET API on http://statistics.restcomm.com/rest/counter/1471167956/1471945556/sip-invites but it didn't return anything

actually I just noticed the timestamp is in seconds so using http://statistics.restcomm.com/rest/counter/1471167956000/1471945556000/sip-invites made it work. 

Is there a Rest API for having a concatenated aggregated number of the counters over the period ?

**Comment by rlimonta** [comment] 2016-08-24 14:23
@deruelle Jean, I made a test on my environment and is working properly. 

I have one suggestion for you simmulate quickly.

01) Change your Remote Server on StatsCounterTest class, like bellow:

![restcomm_rlimonta_openshift_countertest](https://cloud.githubusercontent.com/assets/19157645/17933843/00efd6d2-69ec-11e6-8f03-25f11168ff40.png)

I recovered the indicators through the dashboard and rest api:

![restcomm_rlimonta_dashboard](https://cloud.githubusercontent.com/assets/19157645/17933934/61010f5a-69ec-11e6-9ef4-91873d0fa997.png)

![restcomm_rlimonta_openshift_rest](https://cloud.githubusercontent.com/assets/19157645/17933950/69d13498-69ec-11e6-8571-a4215d52de8b.png)

I accessed my environment via ssh, and the data are saved on MongoDB.

![restcomm_rlimonta_openshift](https://cloud.githubusercontent.com/assets/19157645/17934012/b1e35252-69ec-11e6-9ee7-80b32c1ef6c9.png)

![restcomm_rlimonta_openshift_query](https://cloud.githubusercontent.com/assets/19157645/17934024/c3b41f34-69ec-11e6-9c5d-fd36649f9eb2.png)


I'm sending the address of my test environment:
http://rlimonta-restcommstats.rhcloud.com/
user: restcomm
pass: restcomm123

If you want, I can review your environment with you.

**Comment by rlimonta** [comment] 2016-08-24 14:29
@deruelle Jean, about your question:

_"Is there a Rest API for having a concatenated aggregated number of the counters over the period ?"_

The answer is no, but I can implement that. It's simple...

Best regards.

**Comment by deruelle** [comment] 2016-08-24 14:42
> Is  there a Rest API for having a concatenated aggregated number of the counters over the period ?

https://github.com/RestComm/statistics-service/issues/1 done ;)

**Comment by rlimonta** [comment] 2016-08-24 14:48
@deruelle  :)

**Comment by deruelle** [comment] 2016-08-24 14:53
@rlimonta on the dashboard, it works for the current day but if I try to see for a longer period of time the dashboard doesn't seem to display well for some reason. Did you try displaying values for counters inserted like a week before ?

**Comment by rlimonta** [comment] 2016-08-24 15:08
@deruelle This may be happening because of the default grouping in the chart is HH:mm. When you increase the period, it generates a lot of points to zero.

I will improve to support (month, day, hour, minute).

**Comment by deruelle** [comment] 2016-08-25 17:41
@rlimonta also the UI seems broken under Firefox. Chrome doesn't display well as it does in your case either on Linux.

**Comment by rlimonta** [comment] 2016-08-25 19:36
@deruelle I'll check it out today.

**Comment by rlimonta** [comment] 2016-08-31 02:11
@deruelle I implemented the following items:
01) Firefox Issue: Fixed
02) Dashbord Layout Improvement: Fixed
03) Issue #1: Closed.

**Comment by deruelle** [comment] 2016-09-02 14:25
Thanks @rlimonta !
Confirmed it works fine now !

**Closed** 2017-02-12 17:02 UTC
Labels: Cloud Ops, Help Wanted, High-Priority, Monitoring and Management, RaaS-Alpha2
