### ISSUE TITLE
When you add a contact that already exist you shouldn't have it twice

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/Restcomm-Connect#1869] opened 2017-02-21 11:31 UTC
@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/olympus/issues/92)

We need an alarm when someone is entering a contact that already exist. This way we will not have the problem of having the same contact many times.

---

@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/olympus/issues/92#issuecomment-281310009)

moved here from design repository

**Comment by ipsilantide** [comment] 2017-02-21 11:31
moved here from design repository

**Comment by ammendonca** [comment] 2017-12-07 15:39
Duplicate of https://github.com/RestComm/olympus/issues/92, and it's fixed.

**Closed by ammendonca** 2017-12-07 15:39 UTC
Labels: 1. Bug, Dashboard
