### ISSUE TITLE
Calls to Restcomm

### ISSUE THREAD

**Issue by Nyasak** [RestComm/Restcomm-Connect#2811] opened 2018-02-09 18:27 UTC
I have setup my restcomm using docker pulled the latest image but however SIP calls are being rejected  and the following are the logs

18:22:30,711 INFO  [gov.nist.javax.sip.parser.NioPipelineParser] (pool-AffinityJAIN-thread-27) serving msg on call id dfb7f33b84e79a21ba60d04e36ef7afa@172.18.0.2
restcomm_1  | 18:22:30,717 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (pool-AffinityJAIN-thread-27) <message
restcomm_1  | from="192.168.42.109:49602"
restcomm_1  | to="172.18.0.2:5083"
restcomm_1  | time="1518200550714"
restcomm_1  | isSender="false"
restcomm_1  | transactionId="z9hg4bkc78dc8b6_57a5b08a_e37808ae-116f-46b0-ba93-aa9619f4c80b"
restcomm_1  | callId="dfb7f33b84e79a21ba60d04e36ef7afa@172.18.0.2"
restcomm_1  | firstLine="SIP/2.0 200 OK"
restcomm_1  | >
restcomm_1  | <![CDATA[SIP/2.0 200 OK
restcomm_1  | Call-ID: dfb7f33b84e79a21ba60d04e36ef7afa@172.18.0.2
restcomm_1  | CSeq: 1 OPTIONS
restcomm_1  | From: <sip:restcomm@172.18.0.2>;tag=12942477_37d30613_57a5b08a_c78dc8b6
restcomm_1  | To: <sip:alice@192.168.42.109:49602>;tag=1518200553309
restcomm_1  | Max-Forwards: 70
restcomm_1  | Via: SIP/2.0/WSS 192.168.42.226:5083;branch=z9hG4bKc78dc8b6_57a5b08a_e37808ae-116f-46b0-ba93-aa9619f4c80b;rport
restcomm_1  | Route: <sip:alice@192.168.42.109:49602;transport=wss;lr>
restcomm_1  | Contact: <sip:alice@192.168.42.109:49602;transport=wss>
restcomm_1  | Content-Length: 0
restcomm_1  |
restcomm_1  | ]]>
restcomm_1  | </message>
restcomm_1  |
restcomm_1  | 18:22:30,725 INFO  [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-82) UserAgentManager Processing Message: "org.mobicents.servlet.sip.message.Servlet3SipServletResponseImpl sender : class akka.actor.DeadLetterActorRef self is terminated: false
restcomm_1  | 18:22:30,731 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-11) Invalidating the sip session (12942477_37d30613_57a5b08a_c78dc8b6;dfb7f33b84e79a21ba60d04e36ef7afa@172.18.0.2;c78dc8b6;RestComm)
restcomm_1  | 18:22:30,735 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-11) Invalidating the following sip application session c78dc8b6;RestComm
restcomm_1  | 18:22:30,736 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-11) The following sip application session c78dc8b6;RestComm has been invalidated
restcomm_1  | 18:23:01,216 INFO  [RestCommMediaServer] Global hearbeat is still alive
restcomm_1  | 18:23:30,667 INFO  [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-38) UserAgentManager Processing Message: "akka.actor.ReceiveTimeout$ sender : class akka.actor.DeadLetterActorRef self is terminated: false
restcomm_1  | 18:23:30,695 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (RestComm-akka.actor.default-dispatcher-83) <message
restcomm_1  | from="172.18.0.2:5083"
restcomm_1  | to="192.168.42.109:49602"
restcomm_1  | time="1518200610694"
restcomm_1  | isSender="true"
restcomm_1  | transactionId="z9hg4bkc0deea58_57a5b08a_693e7f91-a7fa-4234-93f5-e6f8cd38a4e9"
restcomm_1  | callId="1f45db796006eebd5b17699ccac60609@172.18.0.2"
restcomm_1  | firstLine="OPTIONS sip:alice@192.168.42.109:49602;transport=wss;lr SIP/2.0"
restcomm_1  | >
restcomm_1  | <![CDATA[OPTIONS sip:alice@192.168.42.109:49602;transport=wss;lr SIP/2.0
restcomm_1  | Call-ID: 1f45db796006eebd5b17699ccac60609@172.18.0.2
restcomm_1  | CSeq: 1 OPTIONS
restcomm_1  | From: <sip:restcomm@172.18.0.2>;tag=09435977_37d30613_57a5b08a_c0deea58
restcomm_1  | To: <sip:alice@192.168.42.109:49602>
restcomm_1  | Max-Forwards: 70
restcomm_1  | User-Agent: Restcomm 8.3.0-140
restcomm_1  | Contact: <sip:restcomm@192.168.42.226:5083;transport=wss>
restcomm_1  | Via: SIP/2.0/WSS 192.168.42.226:5083;branch=z9hG4bKc0deea58_57a5b08a_693e7f91-a7fa-4234-93f5-e6f8cd38a4e9
restcomm_1  | Route: <sip:alice@192.168.42.109:49602;transport=wss;lr>
restcomm_1  | Content-Length: 0
restcomm_1  |
restcomm_1  | ]]>
restcomm_1  | </message>
restcomm_1  |
restcomm_1  | 18:23:30,703 INFO  [gov.nist.javax.sip.parser.NioPipelineParser] (pool-AffinityJAIN-thread-28) serving msg on call id 1f45db796006eebd5b17699ccac60609@172.18.0.2
restcomm_1  | 18:23:30,710 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (pool-AffinityJAIN-thread-28) <message
restcomm_1  | from="192.168.42.109:49602"
restcomm_1  | to="172.18.0.2:5083"
restcomm_1  | time="1518200610709"
restcomm_1  | isSender="false"
restcomm_1  | transactionId="z9hg4bkc0deea58_57a5b08a_693e7f91-a7fa-4234-93f5-e6f8cd38a4e9"
restcomm_1  | callId="1f45db796006eebd5b17699ccac60609@172.18.0.2"
restcomm_1  | firstLine="SIP/2.0 200 OK"
restcomm_1  | >
restcomm_1  | <![CDATA[SIP/2.0 200 OK
restcomm_1  | Call-ID: 1f45db796006eebd5b17699ccac60609@172.18.0.2
restcomm_1  | CSeq: 1 OPTIONS
restcomm_1  | From: <sip:restcomm@172.18.0.2>;tag=09435977_37d30613_57a5b08a_c0deea58
restcomm_1  | To: <sip:alice@192.168.42.109:49602>;tag=1518200613301
restcomm_1  | Max-Forwards: 70
restcomm_1  | Via: SIP/2.0/WSS 192.168.42.226:5083;branch=z9hG4bKc0deea58_57a5b08a_693e7f91-a7fa-4234-93f5-e6f8cd38a4e9;rport
restcomm_1  | Route: <sip:alice@192.168.42.109:49602;transport=wss;lr>
restcomm_1  | Contact: <sip:alice@192.168.42.109:49602;transport=wss>
restcomm_1  | Content-Length: 0
restcomm_1  |
restcomm_1  | ]]>
restcomm_1  | </message>
restcomm_1  |
restcomm_1  | 18:23:30,716 INFO  [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-84) UserAgentManager Processing Message: "org.mobicents.servlet.sip.message.Servlet3SipServletResponseImpl sender : class akka.actor.DeadLetterActorRef self is terminated: false
restcomm_1  | 18:23:30,725 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-12) Invalidating the sip session (09435977_37d30613_57a5b08a_c0deea58;1f45db796006eebd5b17699ccac60609@172.18.0.2;c0deea58;RestComm)
restcomm_1  | 18:23:30,729 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-12) Invalidating the following sip application session c0deea58;RestComm
restcomm_1  | 18:23:30,730 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-12) The following sip application session c0deea58;RestComm has been invalidated
restcomm_1  | 18:24:01,216 INFO  [RestCommMediaServer] Global hearbeat is still alive
restcomm_1  | 18:24:30,667 INFO  [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-38) UserAgentManager Processing Message: "akka.actor.ReceiveTimeout$ sender : class akka.actor.DeadLetterActorRef self is terminated: false
restcomm_1  | 18:24:30,983 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (RestComm-akka.actor.default-dispatcher-85) <message
restcomm_1  | from="172.18.0.2:5083"
restcomm_1  | to="192.168.42.109:49602"
restcomm_1  | time="1518200670983"
restcomm_1  | isSender="true"
restcomm_1  | transactionId="z9hg4bkd3e98421_57a5b08a_04868d8c-c14a-44a3-a393-5dfded75262c"
restcomm_1  | callId="403c94ca74a66c4b58a8a9e61785b5ec@172.18.0.2"
restcomm_1  | firstLine="OPTIONS sip:alice@192.168.42.109:49602;transport=wss;lr SIP/2.0"
restcomm_1  | >
restcomm_1  | <![CDATA[OPTIONS sip:alice@192.168.42.109:49602;transport=wss;lr SIP/2.0
restcomm_1  | Call-ID: 403c94ca74a66c4b58a8a9e61785b5ec@172.18.0.2
restcomm_1  | CSeq: 1 OPTIONS
restcomm_1  | From: <sip:restcomm@172.18.0.2>;tag=90870257_37d30613_57a5b08a_d3e98421
restcomm_1  | To: <sip:alice@192.168.42.109:49602>
restcomm_1  | Max-Forwards: 70
restcomm_1  | User-Agent: Restcomm 8.3.0-140
restcomm_1  | Contact: <sip:restcomm@192.168.42.226:5083;transport=wss>
restcomm_1  | Via: SIP/2.0/WSS 192.168.42.226:5083;branch=z9hG4bKd3e98421_57a5b08a_04868d8c-c14a-44a3-a393-5dfded75262c
restcomm_1  | Route: <sip:alice@192.168.42.109:49602;transport=wss;lr>
restcomm_1  | Content-Length: 0
restcomm_1  |
restcomm_1  | ]]>
restcomm_1  | </message>
restcomm_1  |
restcomm_1  | 18:24:30,998 INFO  [gov.nist.javax.sip.parser.NioPipelineParser] (pool-AffinityJAIN-thread-29) serving msg on call id 403c94ca74a66c4b58a8a9e61785b5ec@172.18.0.2
restcomm_1  | 18:24:31,005 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (pool-AffinityJAIN-thread-29) <message
restcomm_1  | from="192.168.42.109:49602"
restcomm_1  | to="172.18.0.2:5083"
restcomm_1  | time="1518200671005"
restcomm_1  | isSender="false"
restcomm_1  | transactionId="z9hg4bkd3e98421_57a5b08a_04868d8c-c14a-44a3-a393-5dfded75262c"
restcomm_1  | callId="403c94ca74a66c4b58a8a9e61785b5ec@172.18.0.2"
restcomm_1  | firstLine="SIP/2.0 200 OK"
restcomm_1  | >
restcomm_1  | <![CDATA[SIP/2.0 200 OK
restcomm_1  | Call-ID: 403c94ca74a66c4b58a8a9e61785b5ec@172.18.0.2
restcomm_1  | CSeq: 1 OPTIONS
restcomm_1  | From: <sip:restcomm@172.18.0.2>;tag=90870257_37d30613_57a5b08a_d3e98421
restcomm_1  | To: <sip:alice@192.168.42.109:49602>;tag=1518200673596
restcomm_1  | Max-Forwards: 70
restcomm_1  | Via: SIP/2.0/WSS 192.168.42.226:5083;branch=z9hG4bKd3e98421_57a5b08a_04868d8c-c14a-44a3-a393-5dfded75262c;rport
restcomm_1  | Route: <sip:alice@192.168.42.109:49602;transport=wss;lr>
restcomm_1  | Contact: <sip:alice@192.168.42.109:49602;transport=wss>
restcomm_1  | Content-Length: 0
restcomm_1  |
restcomm_1  | ]]>
restcomm_1  | </message>
restcomm_1  |
restcomm_1  | 18:24:31,016 INFO  [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-86) UserAgentManager Processing Message: "org.mobicents.servlet.sip.message.Servlet3SipServletResponseImpl sender : class akka.actor.DeadLetterActorRef self is terminated: false
restcomm_1  | 18:24:31,037 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-13) Invalidating the sip session (90870257_37d30613_57a5b08a_d3e98421;403c94ca74a66c4b58a8a9e61785b5ec@172.18.0.2;d3e98421;RestComm)
restcomm_1  | 18:24:31,037 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-13) Invalidating the following sip application session d3e98421;RestComm
restcomm_1  | 18:24:31,038 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (MSS-Executor-Thread-13) The following sip application session d3e98421;RestComm has been invalidated
restcomm_1  | 18:25:01,216 INFO  [RestCommMediaServer] Global hearbeat is still alive

Anybody got an idea whats happening?

**Comment by gsaslis** [comment] 2018-02-12 10:19
Thanks @Nyasak 

can you please share some more information that will help us better understand and reproduce the issue?

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Comment by Nyasak** [comment] 2018-02-12 10:33
Hi Saslis,
Thanks for the response.

*What happened*: i made a SIP call from a client to +1234 and the call got
rejected

*What you expected to happen*: i expected to hear the standard Restcomm
welcome message

*How to reproduce it (as minimally and precisely as possible)*: 1. Setup up
restcomm using docker-compose

                              2. When the system was up make a call from
SIP client and note the logs



Regards

Doka

**Comment by gsaslis** [comment] 2018-02-12 11:04
Thanks Doka, 

Can you please confirm if peer-to-peer calls work?
Can you try logging into one browser as Bob and into another as Alice and making a call from one to another?

**Comment by Nyasak** [comment] 2018-02-13 07:13
Hi,
Yes Peer to Peer calls are working.

Regards

**Comment by gsaslis** [comment] 2018-02-13 08:54
Thanks @Nyasak ! 

In that case, I am closing as a duplicate of #2778 . Please feel free to reopen if you think this is, in fact, a different one.

**Closed by gsaslis** 2018-02-13 08:55 UTC
