### ISSUE TITLE
Handle integration between RestComm and XMS

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1187] opened 2016-06-14 11:38 UTC
XMS uses lower-case letter for codec name PCMU and PCMA in SDP like following, 
a=rtpmap:0 pcmu/8000 
a=rtpmap:0 pcma/8000

Better to change to upper-case to avoid an unexpected trouble. 
There are some terminals which don't like the format, e.g. Linphone. 
As user commented Dialogic understood the issue but refrained from doing it due to a reason for a backward compatibility.

**Comment by deruelle** [comment] 2016-09-30 16:03
Duplicate of https://github.com/RestComm/Restcomm-Connect/issues/1176

**Closed by deruelle** 2016-09-30 16:03 UTC
Labels: 3. Duplicate, Help Wanted, XMS
