### ISSUE TITLE
Local instance Only Calls Log Search should be removed

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1634] opened 2016-12-08 09:45 UTC
![screenshot from 2016-12-08 10-44-28](https://cloud.githubusercontent.com/assets/54279/21004976/52d6049a-bd33-11e6-94a3-77b5514c293c.png)

There is no reason to have this option as users don't need to know if the service is running on a cluster and they don't have a clue to know on which instance they are.

**Comment by otsakir** [comment] 2016-12-22 15:40
The issue is fixed as of #1676

**Closed by otsakir** 2016-12-22 15:40 UTC
Labels: 2. Enhancement, Admin UI, UI
